<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.3" />
    <PackageReference Include="System.Management" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Management" />
  </ItemGroup>

</Project>
