<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14.0</LangVersion>
    <!-- EXE 文件图标 -->
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <!-- 排除 temp 目录下的所有代码 -->
    <Compile Remove="temp\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="9.*" />
  </ItemGroup>

  <ItemGroup>
       <None Update="config.json">
         <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       </None>
       <!-- 将 assets 目录复制到输出目录 -->
       <None Update="assets\*">
         <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
       </None>
     </ItemGroup>

</Project>